### ISSUE TITLE
CPAN?

### ISSUE THREAD

**Issue by naltun** [saiftynet/GUIDeFATE#1]
Hey @saiftynet, will you be adding GUIDeFATE to CPAN eventually?

Congrats on the cool project! I already have an idea for my first project. ;)

**Comment by saiftynet** [comment]
Dear Noah,

Glad you like it.  I confess I am a newbie, so your suggestions would be
invaluable.
I hope I can get it to a standard where it will be on CPAN.  You advice
would be appreciated.

Best wishes

Saif

**Comment by saiftynet** [comment]
Dear Noah,

Glad you like it.  I confess I am a newbie, so your suggestions would be invaluable.
I hope I can get it to a standard where it will be on CPAN.  You advice would be appreciated.
Also if you would like a feature specific for your project, then of course I will try and accommodate.

Best wishes

Saif

**Comment by matthewpersico** [comment]
https://www.cpan.org/modules/04pause.html

https://pause.perl.org/pause/query

**Comment by matthewpersico** [comment]
https://stackoverflow.com/questions/1731089/how-do-i-get-started-writing-a-module-for-cpan

**Comment by matthewpersico** [comment]
This is OLD, but it has the basics. Read this, http://www.perlmonks.org/?node_id=158999, then look at the ones above.

**Comment by matthewpersico** [comment]
Aha!  http://perldoc.perl.org/perlnewmod.html

Or perldoc perlnewmod on your local machine.

**Comment by saiftynet** [comment]
@matthewpersico Thanks for those helpful resources.  Expect version 0.05 to be up shortly, now that I have worked out how to incorporate the use of different back-end  GUI frameworks from the same module.

**Comment by saiftynet** [comment]
Ok I have created aMANIFEST, Produced a pod present both in GUIDeFATE.pm and as a separate pod file, have created Makefile.PL, did `make dist`, and used `cpan-upload` to upload version 0.05 to CPAN.
